"""Catalog-backed Telegram model picker helpers.

The aiogram dispatcher owns message delivery, but the model picker itself is
pure data: button labels, callback payloads, and the current conversation
model.  Keeping that logic here makes the Telegram UX testable without a bot.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from html import escape
from typing import Protocol

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.providers.catalog import CATALOG_ETAG, MODEL_CATALOG, ModelEntry, default_model
from app.crud.channel import get_or_create_telegram_conversation_full, get_user_id_for_external

PROVIDER = "telegram"
MODEL_CALLBACK_PREFIX = "mdl:"
_CATALOG_TOKEN = CATALOG_ETAG[:8]
_MODEL_PAGE_SIZE = 8
_PROVIDER_BUTTONS_PER_ROW = 2
_CALLBACK_PART_COUNT = 4

_PICKER_NOT_BOUND_MESSAGE = "Connect your account first before changing models."
_PICKER_STALE_MESSAGE = "That model picker is out of date. Open /models again."


class TelegramSenderLike(Protocol):
    """Subset of ``TelegramSender`` used by picker state resolution."""

    user_id: int
    thread_id: int | None


@dataclass(frozen=True)
class ModelButton:
    """One Telegram inline keyboard button."""

    text: str
    callback_data: str


@dataclass(frozen=True)
class ModelPickerState:
    """Current catalog state for one Telegram conversation."""

    current_model_id: str


@dataclass(frozen=True)
class ModelCallback:
    """Parsed Telegram callback payload for the model picker."""

    action: str
    provider: str | None = None
    page: int = 1
    index: int | None = None
    catalog_token: str | None = None


async def get_model_picker_state(
    *,
    sender: TelegramSenderLike,
    session: AsyncSession,
) -> ModelPickerState | None:
    """Resolve the current model for a Telegram sender.

    Returns:
        ``None`` when the Telegram sender is not bound to a Pawrrtal user.
    """
    nexus_user_id = await get_user_id_for_external(
        provider=PROVIDER,
        external_user_id=str(sender.user_id),
        session=session,
    )
    if nexus_user_id is None:
        return None

    conversation = await get_or_create_telegram_conversation_full(
        user_id=nexus_user_id,
        session=session,
        thread_id=sender.thread_id,
    )
    return ModelPickerState(current_model_id=conversation.model_id or default_model().id)


def build_provider_keyboard() -> list[list[ModelButton]]:
    """Build a two-column provider picker from the catalog."""
    rows: list[list[ModelButton]] = []
    current_row: list[ModelButton] = []
    for provider, entries in _grouped_catalog().items():
        current_row.append(
            ModelButton(
                text=f"{_provider_label(provider)} ({len(entries)})",
                callback_data=_list_callback(provider, 1),
            )
        )
        if len(current_row) == _PROVIDER_BUTTONS_PER_ROW:
            rows.append(current_row)
            current_row = []
    if current_row:
        rows.append(current_row)
    return rows


def build_models_keyboard(
    *,
    provider: str,
    page: int,
    current_model_id: str,
) -> list[list[ModelButton]]:
    """Build a paginated model keyboard for one provider."""
    entries = _grouped_catalog().get(provider, [])
    page_count = _page_count(entries)
    page = _clamped_page(page, page_count)
    page_entries = _page_entries(entries, page)

    rows = [
        [
            ModelButton(
                text=_model_label(entry, current_model_id),
                callback_data=_select_callback(_catalog_index(entry)),
            )
        ]
        for entry in page_entries
    ]
    rows.extend(_pagination_rows(provider=provider, page=page, page_count=page_count))
    rows.append([ModelButton(text="Back to providers", callback_data=_providers_callback())])
    return rows


def has_provider(provider: str) -> bool:
    """Return whether the catalog has at least one model for ``provider``."""
    return provider in _grouped_catalog()


def format_provider_picker_text(current_model_id: str) -> str:
    """Render the provider picker message in Telegram HTML."""
    current = _display_name_for_model(current_model_id)
    return f"Choose a model for this Telegram conversation.\n\nCurrent: <b>{escape(current)}</b>"


def format_models_picker_text(
    *,
    provider: str,
    page: int,
) -> str:
    """Render the model page header in Telegram HTML."""
    entries = _grouped_catalog().get(provider, [])
    page_count = _page_count(entries)
    page = _clamped_page(page, page_count)
    label = _provider_label(provider)
    return f"Select a {escape(label)} model.\nPage {page}/{page_count}"


def parse_model_callback_data(data: str | None) -> ModelCallback | None:
    """Parse Telegram callback data generated by this module."""
    if data == _providers_callback() or data == "mdl:b":
        return ModelCallback(action="providers")
    if data is None or not data.startswith(MODEL_CALLBACK_PREFIX):
        return None

    parts = data.split(":")
    if len(parts) == _CALLBACK_PART_COUNT and parts[1] == "l":
        return _parse_list_callback(parts)
    if len(parts) == _CALLBACK_PART_COUNT and parts[1] == "s":
        return _parse_select_callback(parts)
    return None


def resolve_model_selection(callback: ModelCallback) -> ModelEntry | None:
    """Resolve a parsed selection callback to a catalog entry.

    Returns ``None`` for stale catalog tokens or invalid indexes.
    """
    if callback.action != "select" or callback.catalog_token != _CATALOG_TOKEN:
        return None
    if callback.index is None or callback.index < 0:
        return None
    if callback.index >= len(MODEL_CATALOG):
        return None
    return MODEL_CATALOG[callback.index]


def picker_not_bound_message() -> str:
    """Return the not-bound message for picker entry points."""
    return _PICKER_NOT_BOUND_MESSAGE


def picker_stale_message() -> str:
    """Return the stale-picker callback message."""
    return _PICKER_STALE_MESSAGE


def _grouped_catalog() -> dict[str, list[ModelEntry]]:
    providers: dict[str, list[ModelEntry]] = {}
    for entry in MODEL_CATALOG:
        providers.setdefault(entry.vendor.value, []).append(entry)
    return dict(sorted(providers.items()))


def _provider_label(provider: str) -> str:
    return provider.replace("-", " ").title()


def _model_label(entry: ModelEntry, current_model_id: str) -> str:
    prefix = "Selected: " if entry.id == current_model_id else ""
    return f"{prefix}{entry.display_name}"


def _display_name_for_model(model_id: str) -> str:
    for entry in MODEL_CATALOG:
        if entry.id == model_id:
            return entry.display_name
    return model_id


def _catalog_index(entry: ModelEntry) -> int:
    return MODEL_CATALOG.index(entry)


def _providers_callback() -> str:
    return "mdl:p"


def _list_callback(provider: str, page: int) -> str:
    return f"mdl:l:{provider}:{page}"


def _select_callback(index: int) -> str:
    return f"mdl:s:{_CATALOG_TOKEN}:{index}"


def _parse_list_callback(parts: list[str]) -> ModelCallback | None:
    try:
        page = int(parts[3])
    except ValueError:
        return None
    if page < 1:
        return None
    return ModelCallback(action="list", provider=parts[2], page=page)


def _parse_select_callback(parts: list[str]) -> ModelCallback | None:
    try:
        index = int(parts[3])
    except ValueError:
        return None
    return ModelCallback(
        action="select",
        index=index,
        catalog_token=parts[2],
    )


def _page_count(entries: list[ModelEntry]) -> int:
    return max(1, math.ceil(len(entries) / _MODEL_PAGE_SIZE))


def _clamped_page(page: int, page_count: int) -> int:
    return min(max(page, 1), page_count)


def _page_entries(entries: list[ModelEntry], page: int) -> list[ModelEntry]:
    start = (page - 1) * _MODEL_PAGE_SIZE
    return entries[start : start + _MODEL_PAGE_SIZE]


def _pagination_rows(
    *,
    provider: str,
    page: int,
    page_count: int,
) -> list[list[ModelButton]]:
    if page_count <= 1:
        return []

    row = [
        ModelButton(text="< Prev", callback_data=_list_callback(provider, page - 1)),
        ModelButton(text=f"{page}/{page_count}", callback_data=_list_callback(provider, page)),
        ModelButton(text="Next >", callback_data=_list_callback(provider, page + 1)),
    ]
    return [row]
