import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, test } from 'vitest';
import type { MergedSkill } from '../src/merge';
import type { FileDiff } from '../src/output';
import { checkSkills, formatDiffs, writeSkills } from '../src/output';

const generatedHeader = '<!-- AUTO-GENERATED by skill-gen -- DO NOT EDIT -->';
const temporaryDirs: string[] = [];

type SkillInput = {
  name: string;
  description?: string;
  extraFrontmatter?: string[];
  body?: string;
  sources?: string[];
};

/**
 * Builds a merged skill with stable defaults.
 * @param input Skill fields to override.
 * @returns A merged skill.
 */
function mergedSkill(input: SkillInput): MergedSkill {
  return {
    name: input.name,
    description: input.description ?? `${input.name} description`,
    extraFrontmatter: input.extraFrontmatter ?? [],
    body: input.body ?? `# ${input.name}`,
    sources: input.sources ?? [`src/${input.name}.ts`],
  };
}

/**
 * Builds a map keyed by skill name.
 * @param skills Skills to include.
 * @returns A merged skill map.
 */
function skillMap(skills: MergedSkill[]): Map<string, MergedSkill> {
  return new Map(skills.map((skill) => [skill.name, skill]));
}

/**
 * Creates a temporary output directory tracked for cleanup.
 * @returns The created directory path.
 */
async function makeTempDir(): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), 'skill-gen-test-'));
  temporaryDirs.push(dir);
  return dir;
}

afterEach(async () => {
  const dirs = temporaryDirs.splice(0);
  await Promise.all(dirs.map((dir) => rm(dir, { recursive: true, force: true })));
});

describe('writeSkills', () => {
  test('creates a SKILL.md file with generated frontmatter and sources', async () => {
    const outputDir = await makeTempDir();
    const skill = mergedSkill({
      name: 'testing',
      description: 'Testing skill.',
      body: '# Testing\n\nUse deterministic tests.',
      sources: ['src/a.ts', 'src/b.ts'],
    });

    await writeSkills(skillMap([skill]), outputDir);

    await expect(readFile(join(outputDir, 'testing', 'SKILL.md'), 'utf-8')).resolves.toBe(
      `---\nname: testing\ndescription: "Testing skill."\n---\n\n${generatedHeader}\n<!-- Source: src/a.ts -->\n<!-- Source: src/b.ts -->\n\n# Testing\n\nUse deterministic tests.\n`
    );
  });

  test('preserves extra frontmatter after generated description', async () => {
    const outputDir = await makeTempDir();
    const skill = mergedSkill({
      name: 'testing',
      description: 'Testing skill.',
      extraFrontmatter: ['paths:', '  - "backend/**/*.py"'],
      body: '# Testing',
      sources: ['src/a.ts'],
    });

    await writeSkills(skillMap([skill]), outputDir);

    await expect(readFile(join(outputDir, 'testing', 'SKILL.md'), 'utf-8')).resolves.toBe(
      `---\nname: testing\ndescription: "Testing skill."\npaths:\n  - "backend/**/*.py"\n---\n\n${generatedHeader}\n<!-- Source: src/a.ts -->\n\n# Testing\n`
    );
  });

  test('refuses to overwrite handwritten skill files', async () => {
    const outputDir = await makeTempDir();
    await mkdir(join(outputDir, 'manual'), { recursive: true });
    await writeFile(join(outputDir, 'manual', 'SKILL.md'), '# Handwritten skill\n', 'utf-8');

    await expect(writeSkills(skillMap([mergedSkill({ name: 'manual' })]), outputDir)).rejects.toThrow(
      'Refusing to overwrite'
    );
  });

  test('rejects invalid skill names before writing files', async () => {
    const outputDir = await makeTempDir();
    const invalidNames = ['../escape', 'bad/name', 'bad\\name', '.hidden'];

    await Promise.all(
      invalidNames.map((name) =>
        expect(writeSkills(skillMap([mergedSkill({ name })]), outputDir)).rejects.toThrow(
          `Invalid skill name '${name}'`
        )
      )
    );
  });
});

describe('checkSkills', () => {
  test('reports missing, changed, and stale generated files', async () => {
    const outputDir = await makeTempDir();
    const missing = mergedSkill({ name: 'missing', body: 'Missing body.' });
    const changed = mergedSkill({ name: 'changed', body: 'Expected body.' });

    await mkdir(join(outputDir, 'changed'), { recursive: true });
    await writeFile(join(outputDir, 'changed', 'SKILL.md'), `${generatedHeader}\nActual body.\n`, 'utf-8');
    await mkdir(join(outputDir, 'stale'), { recursive: true });
    await writeFile(join(outputDir, 'stale', 'SKILL.md'), `${generatedHeader}\nStale body.\n`, 'utf-8');

    const diffs = await checkSkills(skillMap([missing, changed]), outputDir);
    const byFile = new Map(diffs.map((diff) => [diff.file, diff]));

    expect(byFile.get('missing/SKILL.md')).toMatchObject({
      file: 'missing/SKILL.md',
      type: 'missing',
    });
    expect(byFile.get('changed/SKILL.md')).toMatchObject({
      file: 'changed/SKILL.md',
      type: 'changed',
      actual: `${generatedHeader}\nActual body.\n`,
    });
    expect(byFile.get('stale/SKILL.md')).toEqual({
      file: 'stale/SKILL.md',
      type: 'stale',
    });
  });

  test('rejects invalid skill names before checking files', async () => {
    const outputDir = await makeTempDir();
    const invalidNames = ['../escape', 'bad/name', 'bad\\name', '.hidden'];

    await Promise.all(
      invalidNames.map((name) =>
        expect(checkSkills(skillMap([mergedSkill({ name })]), outputDir)).rejects.toThrow(
          `Invalid skill name '${name}'`
        )
      )
    );
  });
});

describe('formatDiffs', () => {
  test('formats missing, changed, and stale diffs for CLI output', () => {
    const diffs: FileDiff[] = [
      { file: 'missing/SKILL.md', type: 'missing' },
      {
        file: 'changed/SKILL.md',
        type: 'changed',
        expected: 'line one\nline two\n',
        actual: 'line one\nold two\n',
      },
      { file: 'stale/SKILL.md', type: 'stale' },
    ];

    expect(formatDiffs(diffs)).toBe(
      [
        'MISSING: missing/SKILL.md (would be created by generate)',
        'CHANGED: changed/SKILL.md',
        '  - old two',
        '  + line two',
        'STALE: stale/SKILL.md (no longer has source fragments, should be removed)',
      ].join('\n')
    );
  });
});
