/**
 * Full-featured chat input: files, shortcuts, and controller context.
 *
 * @fileoverview AI Elements — `prompt-input`.
 */

export {
	PromptInputActionAddAttachments,
	type PromptInputActionAddAttachmentsProps,
	PromptInputAttachment,
	type PromptInputAttachmentProps,
	PromptInputAttachments,
	type PromptInputAttachmentsProps,
} from './prompt-input-attachments';
export {
	type AttachmentsContext,
	LocalAttachmentsContext,
	PromptInputController,
	type PromptInputControllerProps,
	PromptInputProvider,
	type PromptInputProviderProps,
	type TextInputContext,
	useOptionalPromptInputController,
	useOptionalProviderAttachments,
	usePromptInputAttachments,
	usePromptInputController,
	useProviderAttachments,
} from './prompt-input-context';
export { PromptInput, type PromptInputMessage, type PromptInputProps } from './prompt-input-form';
export {
	PromptInputActionMenu,
	PromptInputActionMenuContent,
	type PromptInputActionMenuContentProps,
	PromptInputActionMenuItem,
	type PromptInputActionMenuItemProps,
	type PromptInputActionMenuProps,
	PromptInputActionMenuTrigger,
	type PromptInputActionMenuTriggerProps,
	PromptInputBody,
	type PromptInputBodyProps,
	PromptInputButton,
	type PromptInputButtonProps,
	PromptInputCommand,
	PromptInputCommandEmpty,
	type PromptInputCommandEmptyProps,
	PromptInputCommandGroup,
	type PromptInputCommandGroupProps,
	PromptInputCommandInput,
	type PromptInputCommandInputProps,
	PromptInputCommandItem,
	type PromptInputCommandItemProps,
	PromptInputCommandList,
	type PromptInputCommandListProps,
	type PromptInputCommandProps,
	PromptInputCommandSeparator,
	type PromptInputCommandSeparatorProps,
	PromptInputFooter,
	type PromptInputFooterProps,
	PromptInputHeader,
	type PromptInputHeaderProps,
	PromptInputHoverCard,
	PromptInputHoverCardContent,
	type PromptInputHoverCardContentProps,
	type PromptInputHoverCardProps,
	PromptInputHoverCardTrigger,
	type PromptInputHoverCardTriggerProps,
	PromptInputSelect,
	PromptInputSelectContent,
	type PromptInputSelectContentProps,
	PromptInputSelectItem,
	type PromptInputSelectItemProps,
	type PromptInputSelectProps,
	PromptInputSelectTrigger,
	type PromptInputSelectTriggerProps,
	PromptInputSelectValue,
	type PromptInputSelectValueProps,
	PromptInputSubmit,
	type PromptInputSubmitProps,
	PromptInputTab,
	PromptInputTabBody,
	type PromptInputTabBodyProps,
	PromptInputTabItem,
	type PromptInputTabItemProps,
	PromptInputTabLabel,
	type PromptInputTabLabelProps,
	type PromptInputTabProps,
	PromptInputTabsList,
	type PromptInputTabsListProps,
	PromptInputTools,
	type PromptInputToolsProps,
} from './prompt-input-layout';
export {
	PromptInputSpeechButton,
	type PromptInputSpeechButtonProps,
} from './prompt-input-speech';
export { PromptInputTextarea, type PromptInputTextareaProps } from './prompt-input-textarea';
