#!/usr/bin/env bun

//<skill-gen>
// ---
// name: skill-gen
// description: "Use when adding, modifying, generating, checking, or debugging repo-local skill fragments embedded in source code with //<skill-gen> markers."
// ---
//
// # skill-gen
//
// Scans source files for `//<skill-gen>` markers, extracts skill fragments (markdown with YAML frontmatter), merges them by skill name, and writes `SKILL.md` files to the configured output folder. Pawrrtal's repo scripts target `.cursor/plugins/pawrrtal/skills`.
//
// **Full specification:** `packages/ci/skill-gen/SPEC.md`
//
// ## Quick Reference
//
// ### Fragment Format
//
// Embed skill fragments in any source file using comment markers:
//
// ```ts
// //<skill-gen>
// // ---
// // name: my-skill
// // description: "What this skill teaches agents."
// // ---
// //
// // ## Section Heading
// //
// // Markdown body content here.
// //</skill-gen>
// ```
//
// - **`name`** (required): identifies which skill this fragment belongs to. Fragments sharing the same name are merged.
// - **`description`** (required): used in the generated SKILL.md frontmatter.
// - Extra frontmatter such as `paths:` is preserved in generated output.
// - Comment prefixes (`//` or `#`) are stripped automatically.
//
// ### Template Variables
//
// | Variable | Expands to |
// |----------|------------|
// | `\$$file` | Relative path from repo root to the source file |
// | `\$$directory` | Relative path from repo root to the source file's directory |
//
// Use `\$$` to produce a literal `\$$file` / `\$$directory` in the output.
//
// ### CLI Commands
//
// ```bash
// # Generate skill files from source fragments
// bun run skill-gen:generate
//
// # Check if generated skills are up-to-date (CI mode)
// bun run skill-gen:check
//
// # Run e2e tests against fixtures
// bun run skill-gen:e2e-test
// ```
//
// ### Merge Rules
//
// | Field | Strategy |
// |-------|----------|
// | `name` | Must match (merge key) |
// | `description` | Last writer wins (warns if different) |
// | extra frontmatter | Later non-empty declarations win (warns if different) |
// | body | Concatenated in source-file order (sorted by relative path) |
//
// ### Key Behaviors
//
// - Fragments without valid `name`/`description` frontmatter are silently skipped.
// - Hand-written SKILL.md files (without `AUTO-GENERATED` header) are never overwritten.
// - The `references/` subdirectory is not managed by skill-gen -- those remain hand-written.
// - Output files include `<!-- AUTO-GENERATED by skill-gen -- DO NOT EDIT -->` header with source file paths.
//
// ### Project Layout
//
// ```
// packages/ci/skill-gen/
//   SPEC.md               full specification
//   src/
//     index.ts            Effect v4 CLI entrypoint
//     scan.ts             file tree walker + fragment extractor
//     parse.ts            comment stripping + frontmatter parsing
//     merge.ts            merge logic (concatenate bodies)
//     output.ts           write / diff output files
//     e2e.ts              e2e fixture comparison (collect/compare SKILL.md files)
//   e2e-test/             test input fixtures
//   e2e-test-expected/    expected output for e2e comparison
// ```
//</skill-gen>

/**
 * skill-gen
 *
 * Scans source files for skill-gen markers, extracts skill fragments
 * (markdown with YAML frontmatter), merges them by skill name, and writes
 * SKILL.md files to the configured output folder.
 *
 * See SPEC.md for full details.
 */

import { execSync } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, resolve } from 'node:path';
import * as NodeServices from '@effect/platform-node/NodeServices';
import * as Console from 'effect/Console';
import * as Effect from 'effect/Effect';
import * as Option from 'effect/Option';
import * as Command from 'effect/unstable/cli/Command';
import * as Flag from 'effect/unstable/cli/Flag';
import { collectSkillFiles, compareFile } from './e2e';
import { mergeFragments } from './merge';
import { checkSkills, formatDiffs, writeSkills } from './output';
import { parseFragment } from './parse';
import { scan } from './scan';

/**
 * Detect git repo root, falling back to cwd.
 */
function detectRepoRoot(): string {
  try {
    return execSync('git rev-parse --show-toplevel', {
      encoding: 'utf-8',
    }).trim();
  } catch {
    return process.cwd();
  }
}

/** Produce merged skills for a base directory, skipping the output directory. */
async function runPipeline(
  baseDir: string,
  outputDir: string,
  verbose: boolean
): Promise<ReturnType<typeof mergeFragments>> {
  const rawFragments = await scan(baseDir, outputDir, verbose);

  if (verbose) {
    process.stdout.write(`pipeline: found ${rawFragments.length} raw fragment(s)\n`);
  }

  const parsed = rawFragments.map(parseFragment).filter((f): f is NonNullable<typeof f> => f !== null);
  const merged = mergeFragments(parsed);

  if (verbose) {
    process.stdout.write(`pipeline: merged into ${merged.size} skill(s)\n`);
  }

  return merged;
}

/** Resolve the default output directory for a base directory. */
function defaultOutputDir(baseDir: string): string {
  return resolve(baseDir, '.agents', 'skills');
}

const baseFlag = Flag.string('base').pipe(
  Flag.optional,
  Flag.withDescription('Base folder to scan (default: git repo root)')
);

const outputFlag = Flag.string('output').pipe(
  Flag.optional,
  Flag.withDescription('Output folder for generated skills')
);

const verboseFlag = Flag.boolean('verbose').pipe(
  Flag.withDefault(false),
  Flag.withDescription('Print discovered fragments and merge diagnostics')
);

/** Generate skills for the requested base/output pair. */
const generate = Command.make('generate', {
  base: baseFlag,
  output: outputFlag,
  verbose: verboseFlag,
}).pipe(
  Command.withHandler(({ base, output, verbose }) =>
    Effect.gen(function* () {
      const baseDir = Option.getOrElse(base, detectRepoRoot);
      const outputDir = Option.getOrElse(output, () => defaultOutputDir(baseDir));
      const merged = yield* Effect.promise(() => runPipeline(baseDir, outputDir, verbose));

      yield* Effect.promise(() => writeSkills(merged, outputDir, verbose));
      yield* Console.log(`generate: wrote ${merged.size} skill(s) to ${outputDir}`);
    })
  )
);

/** Check generated skills against the files on disk. */
const check = Command.make('check', {
  base: baseFlag,
  output: outputFlag,
  verbose: verboseFlag,
}).pipe(
  Command.withHandler(({ base, output, verbose }) =>
    Effect.gen(function* () {
      const baseDir = Option.getOrElse(base, detectRepoRoot);
      const outputDir = Option.getOrElse(output, () => defaultOutputDir(baseDir));
      const merged = yield* Effect.promise(() => runPipeline(baseDir, outputDir, verbose));
      const diffs = yield* Effect.promise(() => checkSkills(merged, outputDir));

      if (diffs.length === 0) {
        yield* Console.log('check: all skills are up-to-date');
        return;
      }

      yield* Console.error(`check: ${diffs.length} difference(s) found`);
      yield* Console.error(formatDiffs(diffs));
      process.exitCode = 1;
    })
  )
);

/** Run the fixture-based end-to-end generator check. */
const e2eTest = Command.make('e2e-test', {
  verbose: verboseFlag,
}).pipe(
  Command.withHandler(({ verbose }) =>
    Effect.gen(function* () {
      const projectDir = resolve(dirname(new URL(import.meta.url).pathname), '..');
      const testDir = resolve(projectDir, 'e2e-test');
      const expectedDir = resolve(projectDir, 'e2e-test-expected');
      const tmpOutput = mkdtempSync(resolve(tmpdir(), 'skill-gen-e2e-'));

      try {
        const merged = yield* Effect.promise(() => runPipeline(testDir, tmpOutput, verbose));
        yield* Effect.promise(() => writeSkills(merged, tmpOutput, verbose));

        const expectedFiles = yield* Effect.promise(() => collectSkillFiles(expectedDir));
        const results = yield* Effect.promise(() =>
          Promise.all(expectedFiles.map((file) => compareFile(file, expectedDir, tmpOutput)))
        );

        let hasError = results.some((ok) => !ok);
        const actualFiles = yield* Effect.promise(() => collectSkillFiles(tmpOutput));
        for (const file of actualFiles) {
          if (!expectedFiles.includes(file)) {
            yield* Console.error(`FAIL: unexpected file ${file} in output`);
            hasError = true;
          }
        }

        if (hasError) {
          yield* Console.error('e2e-test: FAILED');
          process.exitCode = 1;
          return;
        }

        yield* Console.log('e2e-test: PASSED');
      } finally {
        rmSync(tmpOutput, { recursive: true, force: true });
      }
    })
  )
);

const root = Command.make('skill-gen').pipe(Command.withSubcommands([generate, check, e2eTest]));

Command.run(root, { version: '0.0.1' }).pipe(Effect.provide(NodeServices.layer), Effect.runPromise);
