import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { MergedSkill } from './merge';

const TAG_NAME = 'skill-gen';
const GENERATED_PREFIX = `<!-- AUTO-GENERATED by ${TAG_NAME} -- DO NOT EDIT -->`;

/** Build the auto-generated banner naming the source files for a skill. */
function makeHeader(sources: string[]): string {
	const lines = [GENERATED_PREFIX, ...sources.map((s) => `<!-- Source: ${s} -->`)];
	return lines.join('\n');
}

/**
 * Render a merged skill to the final SKILL.md content.
 */
function renderSkill(skill: MergedSkill): string {
	const header = makeHeader(skill.sources);
	const frontmatter = [
		'---',
		`name: ${skill.name}`,
		`description: "${skill.description.replaceAll('"', '\\"')}"`,
		...skill.extraFrontmatter,
		'---',
	].join('\n');

	const body = skill.body.trimEnd();
	return `${frontmatter}\n\n${header}\n\n${body}\n`;
}

/**
 * Validate that a skill name doesn't contain path traversal sequences.
 */
function validateSkillName(name: string): void {
	if (name.includes('..') || name.includes('/') || name.includes('\\') || name.startsWith('.')) {
		throw new Error(
			`Invalid skill name '${name}': must not contain path traversal characters (.. / \\) or start with a dot`
		);
	}
}

/** Check whether an unknown error is a missing-file error. */
function isEnoent(err: unknown): boolean {
	return err instanceof Error && 'code' in err && err.code === 'ENOENT';
}

/** Guard a write target, throwing if a non-generated file already occupies it. */
async function checkExistingFile(filePath: string): Promise<void> {
	try {
		const existing = await readFile(filePath, 'utf-8');
		if (!existing.includes(GENERATED_PREFIX)) {
			throw new Error(
				`Refusing to overwrite ${filePath}: file exists but was not generated by ${TAG_NAME}. ` +
					`Remove it manually or add the ${TAG_NAME} header.`
			);
		}
	} catch (err) {
		if (isEnoent(err)) {
			return;
		}
		throw err;
	}
}

/** Render and write one skill's SKILL.md, refusing to clobber non-generated files. */
async function writeSingleSkill(
	skill: MergedSkill,
	outputDir: string,
	verbose: boolean
): Promise<void> {
	validateSkillName(skill.name);
	const skillDir = join(outputDir, skill.name);
	const filePath = join(skillDir, 'SKILL.md');

	await checkExistingFile(filePath);
	await mkdir(skillDir, { recursive: true });

	const content = renderSkill(skill);
	await writeFile(filePath, content, 'utf-8');

	if (verbose) {
		process.stdout.write(`output: wrote ${skill.name}/SKILL.md\n`);
	}
}

/**
 * Write each merged skill to its own `<outputDir>/<name>/SKILL.md`.
 *
 * @param skills - Merged skills keyed by name.
 * @param outputDir - Directory under which per-skill subdirectories are created.
 * @param verbose - When true, logs each written file to the console.
 * @returns Resolves once all files are written.
 * @throws Error if a skill name is invalid, or a target file exists that this tool did not generate.
 */
export async function writeSkills(
	skills: Map<string, MergedSkill>,
	outputDir: string,
	verbose = false
): Promise<void> {
	await mkdir(outputDir, { recursive: true });

	await Promise.all(
		[...skills.values()].map((skill) => writeSingleSkill(skill, outputDir, verbose))
	);
}

export interface FileDiff {
	file: string;
	type: 'missing' | 'changed' | 'stale';
	expected?: string;
	actual?: string;
}

/** Compare one skill's rendered output against the file on disk, or undefined if they match. */
async function checkSingleSkill(
	skill: MergedSkill,
	outputDir: string
): Promise<FileDiff | undefined> {
	validateSkillName(skill.name);
	const fileName = `${skill.name}/SKILL.md`;
	const filePath = join(outputDir, fileName);
	const expected = renderSkill(skill);

	let actual: string;
	try {
		actual = await readFile(filePath, 'utf-8');
	} catch {
		return { file: fileName, type: 'missing', expected };
	}

	if (actual !== expected) {
		return { file: fileName, type: 'changed', expected, actual };
	}
	return;
}

/**
 * Find stale skill directories: ones that have the generated header
 * but no longer have any source fragments.
 */
async function findStaleFiles(
	outputDir: string,
	skills: Map<string, MergedSkill>
): Promise<FileDiff[]> {
	const diffs: FileDiff[] = [];
	let entries: string[];
	try {
		entries = await readdir(outputDir);
	} catch {
		return [];
	}

	const checkResults = await Promise.all(
		entries.map(async (entry) => {
			const skillFile = join(outputDir, entry, 'SKILL.md');
			try {
				const content = await readFile(skillFile, 'utf-8');
				if (!content.includes(GENERATED_PREFIX)) {
					return;
				}
			} catch {
				return;
			}

			if (!skills.has(entry)) {
				return {
					file: `${entry}/SKILL.md`,
					type: 'stale',
				} satisfies FileDiff;
			}
			return;
		})
	);

	for (const result of checkResults) {
		if (result) {
			diffs.push(result);
		}
	}

	return diffs;
}

/**
 * Compare the expected skill output against the files on disk without writing.
 *
 * @param skills - Merged skills keyed by name.
 * @param outputDir - Directory holding the generated skill files to check.
 * @returns Missing, changed, and stale diffs; an empty array means everything is up-to-date.
 * @throws Error if a skill name is invalid.
 */
export async function checkSkills(
	skills: Map<string, MergedSkill>,
	outputDir: string
): Promise<FileDiff[]> {
	const skillResults = await Promise.all(
		[...skills.values()].map((skill) => checkSingleSkill(skill, outputDir))
	);

	const diffs: FileDiff[] = skillResults.filter((d): d is FileDiff => d !== undefined);

	const stale = await findStaleFiles(outputDir, skills);
	diffs.push(...stale);

	return diffs;
}

/** Format a one-line notice for a skill file that is absent. */
function formatMissing(diff: FileDiff): string {
	return `MISSING: ${diff.file} (would be created by generate)`;
}

/** Format a skill file diff as a unified-style block of changed lines. */
function formatChanged(diff: FileDiff): string {
	const lines = [`CHANGED: ${diff.file}`];
	const expectedLines = diff.expected?.split('\n') ?? [];
	const actualLines = diff.actual?.split('\n') ?? [];
	const maxLen = Math.max(expectedLines.length, actualLines.length);
	for (let i = 0; i < maxLen; i++) {
		const exp = expectedLines[i] ?? '';
		const act = actualLines[i] ?? '';
		if (exp !== act) {
			if (act) {
				lines.push(`  - ${act}`);
			}
			if (exp) {
				lines.push(`  + ${exp}`);
			}
		}
	}
	return lines.join('\n');
}

/** Format a one-line notice for a generated skill file with no remaining sources. */
function formatStale(diff: FileDiff): string {
	return `STALE: ${diff.file} (no longer has source fragments, should be removed)`;
}

/**
 * Render a list of skill-file diffs as human-readable CLI output.
 *
 * @param diffs - Diffs to format, as returned by {@link checkSkills}.
 * @returns A newline-joined report, one entry per diff.
 */
export function formatDiffs(diffs: FileDiff[]): string {
	return diffs
		.map((diff) => {
			switch (diff.type) {
				case 'missing':
					return formatMissing(diff);
				case 'changed':
					return formatChanged(diff);
				case 'stale':
					return formatStale(diff);
				default:
					return `UNKNOWN: ${diff.file}`;
			}
		})
		.join('\n');
}
