#!/usr/bin/env bash
# Quick dev environment setup for CI agents and new contributors.
#
# Usage:
#   # Interactive — prompts for missing values:
#   bash scripts/setup-dev-env.sh
#
#   # Non-interactive — pass env vars directly:
#   GOOGLE_API_KEY=... AUTH_SECRET=... bash scripts/setup-dev-env.sh
#
# After running, start the dev servers with:
#   just dev              # frontend (port 53001) + backend (port 8000)
#   just dev-telegram     # same, but with Telegram polling enabled
#
# The script is idempotent — safe to re-run. It will not overwrite
# values already set in backend/.env.

set -euo pipefail

BACKEND_ENV="backend/.env"

generate_secret() {
  python3 -c "import secrets; print(secrets.token_hex(32))"
}

generate_fernet_key() {
  python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
    || python3 -c "import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())"
}

echo "=== Pawrrtal Dev Environment Setup ==="

if [ -f "$BACKEND_ENV" ]; then
  echo "Found existing $BACKEND_ENV — preserving current values."
  # shellcheck disable=SC1090
  source "$BACKEND_ENV" 2>/dev/null || true
fi

# Required values — use env vars if provided, else prompt or generate
AUTH_SECRET="${AUTH_SECRET:-$(generate_secret)}"
WORKSPACE_ENCRYPTION_KEY="${WORKSPACE_ENCRYPTION_KEY:-$(generate_fernet_key)}"
GOOGLE_API_KEY="${GOOGLE_API_KEY:-}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@pawrrtal-ai.dev}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-admin1234}"
CORS_ORIGINS="${CORS_ORIGINS:-[\"http://localhost:53001\"]}"
ENV="${ENV:-dev}"

if [ -z "$GOOGLE_API_KEY" ]; then
  echo ""
  echo "GOOGLE_API_KEY is required for Gemini models."
  echo "Get one from https://aistudio.google.com/apikey"
  read -rp "GOOGLE_API_KEY: " GOOGLE_API_KEY
fi

# Optional values
XAI_API_KEY="${XAI_API_KEY:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
OPENCODE_API_KEY="${OPENCODE_API_KEY:-}"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
TELEGRAM_DEV_ADMIN_ID="${TELEGRAM_DEV_ADMIN_ID:-}"

# Write the .env file
cat > "$BACKEND_ENV" << EOF
# Generated by scripts/setup-dev-env.sh — safe to edit
ENV=${ENV}
AUTH_SECRET=${AUTH_SECRET}
WORKSPACE_ENCRYPTION_KEY=${WORKSPACE_ENCRYPTION_KEY}
GOOGLE_API_KEY=${GOOGLE_API_KEY}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
CORS_ORIGINS=${CORS_ORIGINS}
COOKIE_SAMESITE=lax
COOKIE_SECURE=false
EOF

# Append optional keys only if set
[ -n "$XAI_API_KEY" ] && echo "XAI_API_KEY=${XAI_API_KEY}" >> "$BACKEND_ENV"
[ -n "$OPENAI_API_KEY" ] && echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> "$BACKEND_ENV"
[ -n "$OPENCODE_API_KEY" ] && echo "OPENCODE_API_KEY=${OPENCODE_API_KEY}" >> "$BACKEND_ENV"
[ -n "$TELEGRAM_BOT_TOKEN" ] && echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}" >> "$BACKEND_ENV"
[ -n "$TELEGRAM_DEV_ADMIN_ID" ] && echo "TELEGRAM_DEV_ADMIN_ID=${TELEGRAM_DEV_ADMIN_ID}" >> "$BACKEND_ENV"

echo ""
echo "Written $BACKEND_ENV"
echo ""
echo "Next steps:"
echo "  1. just install      # install all dependencies"
echo "  2. just dev           # start frontend (53001) + backend (8000)"
echo "  3. Open http://localhost:53001"
echo "  4. Dev login: POST http://localhost:8000/auth/dev-login"
echo ""
echo "For Telegram: set TELEGRAM_BOT_TOKEN and run 'just dev-telegram'"
EOF
